---
title: About the Workshop
author: Tatjana Kecojevic
date: '2020-02-24'
slug: programme
categories: []
tags:
  - SisterAnalyst
  - ds
  - OpenData
comments: yes
image: ''
menu: ''
share: yes
---

[SisterAnalyst](https://sisteranalyst.org) is pleased to announce our Open Data Challenge Workshop, in partnership with the [Open Heroines](https://openheroines.org/) initiative -  a visible platform for women to express their thoughts, ideas and critiques. 

**When**: Monday, March 09, 2020
5:00 PM to 8:00 PM

**Where**: [AFA](https://www.afa.co.rs), Gospodar Jovanova 2
11000 Belgrade, Serbia

---

##### <span style="color:darkblue">The event is free, but registration is required by [filling this form 👉📄](https://docs.google.com/forms/d/1NtyhRMDZkcyU9AsEXWIq-M5OVWzs1JEwaybx4JI1IPU/edit?ts=5e50f8e4)</span>

---

Our aim is to fully democratise Open Data, we believe that Open Data portals should not simply focus on just providing data. Ideally, they should serve as platforms that harvest open and available knowledge and additionally provide educational resources that enrich the potential of the available data. 

[Sister Analyst](https://sisteranalyst.org) is delivering the Open Data Challenge workshop in Belgrade - a workshop which aims to provide an insightful overview of the data democracy process. Only by creating a working understanding of the processes and procedures involved with data analytics is it possible to create the objective of democratic data literacy. Through the use of free open source data analysis software packages as R and GitHub it is possible to build an understanding of the systems involved in analysing data and the knowledge to make it usable. 

Participants in the workshop will be introduced to different ways of accessing Open Data and will be able to engage in the necessary steps of wrangling and preparation of data for analysis. As such, they'll be given the opportunity to familiarise themselves with typical tools used in a data analysis processes. They will also be able to learn how to communicate the results in a transparent and engaging way by creating dynamic documents and info graphics. Additionally, all the participants will be instructed to the Open Data Challenge platform where they can find the material and learn further to create a free hosting website for the resulting blog posts of their data analysis narratives using HUGO and blogdown.

---

Agenda:

- 5:00pm -- Doors open and refreshments
- 5:15pm -- Welcome to Open Data Challenge Workshop: Introduction, Announcements
- 5:20pm -- Workshop
- 7:30pm -- Hang around: drinks, pizza and a chance to chat
- 8:00pm -- End

---

We would love you to come and join us, bring a friend or two and share your thoughts and experiences when working with Open Data.

All welcome!

We are looking forward to seeing you all…

---

##### Thanks to [Open Heroins](https://openheroines.org) and [AFA](https://www.afa.co.rs) for making this event possible.

